services:
  - type: web
    name: central-team-reg-backend
    env: node
    buildCommand: npm install express # Install express directly in the root for the temporary app
    startCommand: node app.js # Run the temporary app.js in the root
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://central-team-reg.vercel.app
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        value: admin123
      - key: ADMIN_EMAIL
        value: admin@example.com
      - key: PORT
        value: 5000
    healthCheckPath: /
    autoDeploy: true 